post  http://localhost:3009/
Content-Type: application/json


{
    "name": "bhagya",
    "email": "bhagya818gmail.com",
    "id":"1",
    "password":"bhagya123"
}



###
post  http://localhost:3009/login
Content-Type: application/json


{
    "email": "bhagya818gmail.com",
    "password":"bhagya123"
}


### 
post http://localhost:3009/admin
Content-Type: application/json


{
    "name": "admin",
    "email": "admin1234@gmail.com",
    "id":"1",
    "password":"admin12"
}


###
post  http://localhost:3009/adminLogin
Content-Type: application/json


{
    "email": "admin1234@gmail.com",
    "password":"admin12"
}



###
get http://localhost:3009/



###
get http://localhost:3009/getOneData/1






###
put  http://localhost:3009/update/1
Content-Type: application/json


{
    "name": "bhagyaShree",
    "email": "lbhagya818gmail.com",
    "password":"bhagya1234"
}


### 
delete  http://localhost:3009/delete/63dfa644bb5a3335f6aa8315
